# version format
version: 4.8.0.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Build worker image (VM template)
image: Visual Studio 2017

# build cache to preserve files/folders between builds
cache:
  - packages

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: CommonAssemblyInfo.cs
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build_script:
  - build --Configuration:Release --test
