# version format
version: 4.8.0.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Build worker image (VM template)
image: Visual Studio 2017

# build cache to preserve files/folders between builds
cache:
  - '%USERPROFILE%\.nuget\packages'

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

build_script:
  - build.bat --Configuration:Release -v:%APPVEYOR_BUILD_VERSION% -pv:%APPVEYOR_BUILD_VERSION%
  
test_script:
  - build.bat --test
  - ps: build\uploadtests.ps1 "release\TestResults"

artifacts:
  - path: release\NuGetPackages\*.nupkg
